version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:3.8.6
    volumes:
      - $PWD:/srv/jekyll
      - banco-de-dados-bundle-jekyll:/usr/local/bundle
    environment:
      - TZ=America/Sao_Paulo
      - JEKYLL_GID=1000
      - JEKYLL_UID=1000
    ports:
      - "4000:4000"
    command: jekyll server
    tty: true
    stdin_open: true

volumes:
  banco-de-dados-bundle-jekyll:
